# syntax=docker/dockerfile:1

ARG ROS_DISTRO=jazzy
ARG BASE_IMAGE=ghcr.io/launchpad-build/launchpad-ros2-jazzy:main

# ---------------------------------------------------------------------------
# Stage: deps
# ---------------------------------------------------------------------------
FROM ${BASE_IMAGE} AS deps

ARG ROS_DISTRO
ARG PACKAGE_PATH=.

WORKDIR /ws

COPY ${PACKAGE_PATH} src/

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    rosdep update --rosdistro ${ROS_DISTRO} && \
    rosdep install --from-paths src --ignore-src -r -y

# ---------------------------------------------------------------------------
# Stage: build
# ---------------------------------------------------------------------------
FROM deps AS build

RUN --mount=type=cache,target=/ws/build \
    . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build \
      --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      --event-handlers console_cohesion+

# ---------------------------------------------------------------------------
# Stage: test
# ---------------------------------------------------------------------------
FROM build AS test

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    . /ws/install/setup.sh && \
    colcon test \
      --event-handlers console_cohesion+ && \
    colcon test-result --verbose

# ---------------------------------------------------------------------------
# Stage: runtime
# ---------------------------------------------------------------------------
FROM ${BASE_IMAGE} AS runtime

ARG ROS_DISTRO

COPY --from=build /ws/install /ws/install

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    rosdep update --rosdistro ${ROS_DISTRO} && \
    rosdep install --from-paths /ws/install --ignore-src -r -y

WORKDIR /ws

ENTRYPOINT ["/bin/bash", "-c", ". /opt/ros/${ROS_DISTRO}/setup.sh && . /ws/install/setup.sh && exec \"$@\"", "--"]
